general:
  root_path: ../vnncomp2025_benchmarks/benchmarks/cifar100_2024
  csv_name: instances.csv
data:
  num_outputs: 100
  start: 0  # Subject to change.
  end: 10
specification:
  norm: .inf
  epsilon: 0.00784313725490196
attack:
  pgd_order: middle
  pgd_restarts: 10
solver:
  batch_size: 1024
  beta-crown:
    lr_alpha: 0.05
    lr_beta: 0.1
    iteration: 5
  alpha-crown:
    lr_alpha: 0.25
    iteration: 20
bab:
  timeout: 300
  interm_transfer: false
  tree_traversal: depth_first
  branching:
    method: kfsb
    candidates: 7
    reduceop: max
  interm_transfer: false
  cut:
    enabled: true
    bab_cut: true
    number_cuts: 75
    biccos:
      enabled: true
      auto_param: false
      constraint_strengthening: true
      drop_ratio: 0.5
      max_infer_iter: 20
      max_domain: 10000
      heuristic: random_drop
      multi_tree_branching:
        enabled: true
        restore_best_tree: true
        keep_n_best_domains: 50
        target_batch_size: 200
        iterations: 3